### ISSUE TITLE
ImportError: no module named 'usb_hid'

### ISSUE THREAD

**Issue by yogeshjoga** [FLOCK4H/AtomDucky#7]
USB_HID module not working on Seeed Studio XIAO ESP32C3 chip.

throwing importError no module  named as usb_hid, can you please Look into this @FLOCK4H  
very interested to developing firmware's, making more effective Rubber Ducky by using small chips this is my goal

**Comment by FLOCK4H** [comment]
Unfortunately due to a human mistake, the `Seeed Studio XIAO ESP32C3` was put under the supported devices list.

Please, have in mind that the list of supported devices was created by selecting boards that have WiFi & HID functionalities, there is no such list on the internet. I made the supported devices list by looking manually at which boards are in both `wifi` and `usb_hid` circuitpython modules, I will remove that board from the list.

**Comment by FLOCK4H** [comment]
The list was updated, there should be no unsupported boards anymore.
